Finish linter
EndPointCorp/end-point-blog pull request #1740
Opened 2021-05-13 18:28 UTC by obnoxiousorc

2021-05-13 20:13 UTC, jonjensen requested changes
I don't see a way to comment on lines not visible in the diff, but here are a couple of others:

```
bool(re.match(r'.*\t.*', l.line)
```

Since you are looking anywhere in the string, not matching at beginning and end, use `re.search()` instead and you can get rid of the `.*` at the beginning and end.

But also since you're looking for a single character, not a regex, you can use faster regular substring search:

```
l.line.find('\t') >= 0
```

which may be a microoptimization, but oh well.

This appears twice:

```
without_code = re.sub(r'`[^`]*`', '', line.line)
```

seems like it should be ```r'[^`]+'``` that is, always requiring something in the code block, not an empty one, right?

Finally, do you have in mind a clear distinction between warnings and errors? Just curious. I bet on rare occasion we may need to use 3-backtick quoting on a single line when we're quoting a backtick, even though normally we wouldn't want that. And just wondered about how to decide.

2021-05-13 21:46 UTC, obnoxiousorc commented on bin/blog-lint.py
> +            'regex': r'[^\s]/[^​]',
I'm fine with either, and I did also fix the bit you mentioned about `without_code`. Let me know which one you prefer here and I'll push my changes.

2021-05-14 15:38 UTC, jonjensen commented on bin/blog-lint.py
> +            'regex': r'[^\s]/[^​]',
Let's go with explicit `\u200b` then. I think many people will totally miss it otherwise.

2021-05-21 05:48 UTC, jonjensen commented
@obnoxiousorc You're still going to push a new commit to wrap this up, right?

2021-05-21 15:43 UTC, obnoxiousorc commented
@jonjensen Sorry, slipped my mind this week. Pushed now though, looks like the `re` module supports `\u200b` in an `r'...'` string just fine!

2021-05-25 13:18 UTC, merged